### ISSUE TITLE
Auto Update on the UI

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/distribution#72] opened 2024-12-27 02:37 UTC
Hi,

I would like to request a feature, a sort of auto update that not only shows notifications, but let you choose, when or how many times a day to check for updates and if you want to update now or do it later, or even choose certain times to automatically do the update.

Additionally be able to build your updates, besides the default pacman and AUR updates. Let's say I have other commands or a script that may or may not require sudo. Be possible add them.

**Comment by vnepogodin** [comment] 2024-12-27 08:42
Duplicate of https://github.com/CachyOS/distribution/issues/29

You might want to write there

**Closed by vnepogodin** 2024-12-27 08:42 UTC
Labels: enhancement
