### ISSUE TITLE
[Wiki] Verify if x86-64-v3 binaries are actually being used?

### ISSUE THREAD

**Issue by GrabbenD** [CachyOS/distribution#7] opened 2023-07-28 17:44 UTC
I've installed Arch Linux via chroot by following instructions from: https://wiki.archlinux.org/title/installation_guide
From there I added CachyOS repositories using steps from: https://wiki.cachyos.org/en/home/Repo
After completing the installation, I figured most of the system binaries would have to be replaces with x86-64-v3 equivalents but it seems like that didn't happen (as this command completed almost instantly)?

```console
[root@archlinux ~]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 cachyos-v3                                                                                                         96.3 KiB   587 KiB/s 00:00 [#######################################################################################] 100%
 cachyos-core-v3                                                                                                   128.7 KiB  1839 KiB/s 00:00 [#######################################################################################] 100%
 cachyos-extra-v3                                                                                                    4.0 MiB  20.1 MiB/s 00:00 [#######################################################################################] 100%
 cachyos                                                                                                           366.5 KiB  1573 KiB/s 00:00 [#######################################################################################] 100%
:: Starting full system upgrade...
warning: pacman: local (6.0.2-10) is newer than core (6.0.2-7)
 there is nothing to do
```

I also tried this but I don't think it made a difference:
```console
[root@archlinux ~]# pacman -Suuy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 cachyos-v3 is up to date
 cachyos-core-v3 is up to date
 cachyos-extra-v3 is up to date
 cachyos is up to date
:: Starting full system upgrade...
warning: pacman: downgrading from version 6.0.2-10 to version 6.0.2-7
resolving dependencies...
looking for conflicting packages...

Packages (1) pacman-6.0.2-7

Total Installed Size:   4.72 MiB
Net Upgrade Size:      -0.03 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                                                 [#######################################################################################] 100%
(1/1) checking package integrity                                                                                                               [#######################################################################################] 100%
(1/1) loading package files                                                                                                                    [#######################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [#######################################################################################] 100%
(1/1) checking available disk space                                                                                                            [#######################################################################################] 100%
:: Processing package changes...
(1/1) downgrading pacman                                                                                                                       [#######################################################################################] 100%
warning: /etc/pacman.conf installed as /etc/pacman.conf.pacnew
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

For reference:
```console
[root@archlinux ~]# /lib/ld-linux-x86-64.so.2 --help | grep supported
  x86-64-v3 (supported, searched)
  x86-64-v2 (supported, searched)


$ less /etc/pacman.conf
<...>

#[testing]
#Include = /etc/pacman.d/mirrorlist

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[community-testing]
#Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

# If you want to run 32 bit applications on your x86_64 system,
# enable the multilib repositories as required here.

#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist

#[multilib]
#Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#SigLevel = Optional TrustAll
#Server = file:///home/custompkgs

# cachyos repos
## Only add if your CPU does v3 architecture
[cachyos-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist
[cachyos-core-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist
[cachyos-extra-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist
[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist


```

**Is there actually any way to make sure x86-64-v3 binaries from CachyOS repository are being used when installing from Arch?**

**Comment by vnepogodin** [comment] 2023-07-28 18:14
@GrabbenD  You need to place repository on top of arch ones

**Comment by GrabbenD** [comment] 2023-07-28 19:37
Thank you for the fast response @vnepogodin 
I followed your steps and Pacman recognized the new repos:
```console
[root@unix ~]# pacman -Syu
:: Synchronizing package databases...
 cachyos-v3 is up to date
 cachyos-core-v3 is up to date
 cachyos-extra-v3 is up to date
 cachyos is up to date
:: Starting full system upgrade...
warning: curl: local (8.2.1-1) is newer than cachyos-core-v3 (8.2.0-2.1)
warning: grub: local (2:2.12rc1-1) is newer than cachyos-v3 (2:2.06.r499.ge67a551a4-1)
resolving dependencies...
looking for conflicting packages...

Packages (127) acl-2.3.1-3.1  argon2-20190702-5.1  attr-2.5.1-3.1  audit-3.1.1-1.1  bash-5.1.016-4.1  binutils-2.40-10  bluez-libs-5.68-1.1  brotli-1.0.9-12.1  bzip2-1.0.8-5.1  ca-certificates-mozilla-3.91-1.1  coreutils-9.3-1.1
               cryptsetup-2.6.1-3.1  dbus-1.14.8-1.1  debugedit-5.0-5.1  device-mapper-2.03.21-1.1  diffutils-3.10-1.1  duktape-2.7.0-6.1  e2fsprogs-1.47.0-1.1  efibootmgr-18-2.1  efivar-38-3.1  expat-2.5.0-1.1  file-5.44-3.1
               filesystem-2023.01.31-1.1  findutils-4.9.0-3.1  gawk-5.2.2-1.1  gcc-libs-13.1.1-4  gdbm-1.23-2.1  gettext-0.22-1.1  glib2-2.76.4-1.1  glibc-2.37-10  gmp-6.2.1-2.1  gnupg-2.2.41-1.1  gnutls-3.8.0-1.1  gpgme-1.21.0-1.1
               gpm-1.20.7.r38.ge82d1a6-5.1  grep-3.11-1.1  gzip-1.12-2.1  htop-3.2.2-1.1  icu-73.2-2.1  iproute2-6.4.0-1.1  iptables-1:1.8.9-1.1  iputils-20221126-2.1  jansson-2.14-2.1  json-c-0.16-1.1  kbd-2.6.1-1.1  keyutils-1.6.3-2.1
               kmod-30-3.1  krb5-1.20.1-1.1  ldns-1.8.3-2.1  less-1:633-1.1  libarchive-3.7.0-2.1  libassuan-2.5.6-1.1  libbpf-1.2.2-1.1  libcap-2.69-1.1  libcap-ng-0.8.3-2.1  libdaemon-0.14-5.1  libedit-20221030_3.1-1.1
               libelf-0.189-1.1  libffi-3.4.4-1.1  libgcrypt-1.10.2-1.1  libgpg-error-1.47-1.1  libidn2-2.3.4-3.1  libksba-1.6.4-1.1  libldap-2.6.4-2.1  libmm-glib-1.20.6-1.1  libmnl-1.0.5-1.1  libndp-1.8-1.1
               libnetfilter_conntrack-1.0.9-1.1  libnewt-0.52.23-2.1  libnfnetlink-1.0.2-1.1  libnftnl-1.2.5-1.1  libnghttp2-1.55.1-1.1  libnl-3.7.0-3.1  libp11-kit-0.25.0-1.1  libpcap-1.10.4-1.1  libpgm-5.3.128-3.1  libpsl-0.21.2-1.1
               libsasl-2.1.28-4.1  libseccomp-2.5.4-2.1  libsecret-0.20.5-2.1  libsodium-1.0.18-2.1  libssh2-1.11.0-1.1  libsysprof-capture-3.48.0-2.1  libtasn1-4.19.0-1.1  libteam-1.31-8.1  libtirpc-1.3.3-2.1  libunistring-1.1-2.1
               libutempter-1.2.1-3.1  libverto-0.3.2-4.1  libxcrypt-4.4.36-1.1  libxml2-2.11.4-1.1  lz4-1:1.9.4-1.1  mkinitcpio-busybox-1.36.1-1.1  mpfr-4.2.0.p12-1.1  nano-7.2-1.1  ncurses-6.4_20230520-1.1  npth-1.6-4.1  nspr-4.35-1.1
               nss-3.91-1.1  openssh-9.3p2-1.1  openssl-3.1.1-1.1  p11-kit-0.25.0-1.1  pam-1.5.3-3.1  pciutils-3.10.0-1.1  pcre-8.45-3.1  pcre2-10.42-2.1  pcsclite-2.0.0-1.1  pinentry-1.2.1-1.1  polkit-122-1.1  popt-1.19-1.1
               procps-ng-4.0.3-1.1  psmisc-23.6-1.1  readline-8.2.001-2.1  sed-4.9-3.1  shadow-4.13-2.1  slang-2.3.3-2.1  sqlite-3.42.0-1.1  tar-1.35-1.1  tpm2-tss-4.0.1-1.1  tzdata-2023c-2.1  util-linux-2.39.1-1.1
               util-linux-libs-2.39.1-1.1  wget-1.21.4-1.1  wpa_supplicant-2:2.10-8.1  xz-5.4.3-1.1  zlib-1:1.2.13-3.1  zstd-1.5.5-3

Total Download Size:   138.90 MiB
Total Installed Size:  576.42 MiB
Net Upgrade Size:       35.26 MiB

:: Proceed with installation? [Y/n]
```

Just a follow-up question to make sure everything is correct, are some packages like `linux` not optimized for x86-64-v3?
```console
[root@unix ~]# pacman -Qi linux
Installed From  : None
Name            : linux
Version         : 6.4.6.arch1-1
Description     : The Linux kernel and modules
Architecture    : x86_64
URL             : https://github.com/archlinux/linux/commits/v6.4.6-arch1
Licenses        : GPL2
Groups          : None
Provides        : KSMBD-MODULE  VIRTUALBOX-GUEST-MODULES  WIREGUARD-MODULE
Depends On      : coreutils  initramfs  kmod
Optional Deps   : wireless-regdb: to set the correct wireless channels of your country
                  linux-firmware: firmware images needed for some devices [installed]
Required By     : None
Optional For    : base
Conflicts With  : None
Replaces        : virtualbox-guest-modules-arch  wireguard-arch
Installed Size  : 125.44 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Mon Jul 24 22:19:38 2023
Install Date    : Fri Jul 28 18:43:31 2023
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by vnepogodin** [comment] 2023-07-28 19:57
Yep. we don't provide `linux`

**Comment by vnepogodin** [comment] 2023-07-28 19:58
I think the issue is resolved. so I will close it
Feel free to re-open

**Closed by vnepogodin** 2023-07-28 19:58 UTC
